// Generated by CoffeeScript 1.3.1
(function() {
  var hash, hashTimer, rooter;

  hash = {
    listeners: [],
    listen: function(fn) {
      return rooter.hash.listeners.push(fn);
    },
    trigger: function(hash) {
      var fn, _i, _len, _ref;
      if (hash == null) {
        hash = rooter.hash.hash();
      }
      if (hash === "") {
        hash = "/";
      }
      _ref = rooter.hash.listeners;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        fn = _ref[_i];
        fn(hash);
      }
    },
    hash: function(h) {
      if (h) {
        window.location.hash = h;
      }
      return window.location.hash.replace('#', '');
    }
  };

  hashTimer = {
    listeners: [],
    listen: function(fn) {
      return rooter.hash.listeners.push(fn);
    },
    trigger: function(hash) {
      var fn, _i, _len, _ref;
      if (hash == null) {
        hash = rooter.hash.hash();
      }
      if (hash === "") {
        hash = "/";
      }
      _ref = rooter.hash.listeners;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        fn = _ref[_i];
        fn(hash);
      }
    },
    hash: function(h) {
      if (h) {
        rooter.hash.lastHash = h;
        window.location.hash = h;
      }
      return window.location.hash.replace('#', '');
    },
    lastHash: null,
    check: function() {
      var currHash;
      currHash = rooter.hash.hash();
      if (currHash !== rooter.hash.lastHash) {
        rooter.hash.lastHash = currHash;
        rooter.hash.trigger(currHash);
      }
      setTimeout(rooter.hash.check, 100);
    }
  };

  rooter = {
    init: function() {
      rooter.hash.listen(rooter.test);
      if (rooter.hash.check) {
        return rooter.hash.check();
      }
      return rooter.hash.trigger();
    },
    routes: {},
    route: function(expr, fn) {
      var pattern;
      pattern = "^" + expr + "$";
      pattern = pattern.replace(/([?=,\/])/g, '\\$1').replace(/:([\w\d]+)/g, '([^/]*)').replace(/\*([\w\d]+)/g, '(.*?)');
      rooter.routes[expr] = {
        pattern: new RegExp(pattern),
        fn: fn
      };
    },
    test: function(hash) {
      var d, m, r, _ref;
      _ref = rooter.routes;
      for (r in _ref) {
        d = _ref[r];
        if (m = d.pattern.exec(hash)) {
          d.fn.apply(null, m.slice(1));
        }
      }
    }
  };

  if (typeof window !== "undefined" && window !== null) {
    if (typeof window.onhashchange !== 'undefined') {
      console.log('event');
      rooter.hash = hash;
      window.onhashchange = function() {
        return rooter.hash.trigger(rooter.hash.hash());
      };
    } else {
      console.log('timer');
      rooter.hash = hashTimer;
      setTimeout(rooter.hash.check, 100);
    }
    window.rooter = rooter;
  } else if (typeof module !== "undefined" && module !== null) {
    module.exports = rooter;
  }

}).call(this);
